version: "3"
services:
  reverseproxy:
      image: juandavidtorres/reverseproxy
      ports:
          - 80:8080
      restart: always
      depends_on:
        - motor-emparejamiento
  motor-emparejamiento:
    image: juandavidtorres/motor-emparejamiento
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - 5000